name: sgtool-py
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.24
  - scipy>=1.10
  - pandas>=2.0
  - matplotlib>=3.7
  - scikit-learn>=1.3
  - geopandas>=0.13
  - folium>=0.14
  - branca>=0.6
  - pyproj>=3.4
  - pillow>=9.0
  - click>=8.0
  - tqdm>=4.65
  - pykrige>=1.7
  - pywavelets>=1.4
  - rasterio>=1.3
  - pip
  - pip:
    - numba>=0.57  # Optional JIT compilation