name: uxo-wizard-scripts
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.7
  - scipy>=1.10
  - scikit-learn>=1.3
  - geopandas>=0.13
  - folium>=0.14
  - contextily>=1.3
  - pyproj>=3.4
  - pykrige>=1.7
  - pywavelets>=1.4
  - utm>=0.7
  - alphashape>=1.3
  - plotly>=5.0
  - branca>=0.6
  - xyzservices>=2023.10
  - shapely>=2.0
  - pip
  - pip:
    - PyEMD  # Not available in conda, install via pip